import type { PrismaClient } from "@prisma/client"
import { Prisma, CatalogCategory, CatalogItemType, CatalogGender } from "@prisma/client"

export async function seedCatalogItems(prisma: PrismaClient) {
  const location = await prisma.location.findFirst({ select: { id: true } })
  if (!location) {
    throw new Error("No Location found. Create at least one Location before seeding CatalogItem.")
  }

  await prisma.catalogItem.deleteMany({ where: { locationId: location.id } })

  let sortOrder = 0
  const row = (
    item: Omit<
      Prisma.CatalogItemCreateManyInput,
      "locationId" | "isVisible" | "sortOrder" | "createdAt" | "updatedAt"
    >
  ): Prisma.CatalogItemCreateManyInput => ({
    ...item,
    locationId: location.id,
    isVisible: true,
    sortOrder: ++sortOrder,
    serviceId: null,
  })

  const items: Prisma.CatalogItemCreateManyInput[] = [
    // WAX FEMALE face
    row({
      category: CatalogCategory.WAX,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.FEMALE,
      groupKey: "face",
      titleRu: "Верхняя губа",
      subtitleRu: "5 мин",
      price: 400,
      durationMin: 5,
    }),
    row({
      category: CatalogCategory.WAX,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.FEMALE,
      groupKey: "face",
      titleRu: "Подбородок",
      subtitleRu: "5 мин",
      price: 500,
      durationMin: 5,
    }),
    row({
      category: CatalogCategory.WAX,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.FEMALE,
      groupKey: "face",
      titleRu: "Лицо полностью",
      subtitleRu: "25 мин",
      price: 1800,
      durationMin: 25,
    }),
    // WAX FEMALE body
    row({
      category: CatalogCategory.WAX,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.FEMALE,
      groupKey: "body",
      titleRu: "Подмышки",
      subtitleRu: "10 мин",
      price: 700,
      durationMin: 10,
    }),
    row({
      category: CatalogCategory.WAX,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.FEMALE,
      groupKey: "body",
      titleRu: "Предплечья",
      subtitleRu: "20 мин",
      price: 1200,
      durationMin: 20,
    }),
    row({
      category: CatalogCategory.WAX,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.FEMALE,
      groupKey: "body",
      titleRu: "Руки полностью",
      subtitleRu: "30 мин",
      price: 1800,
      durationMin: 30,
    }),
    row({
      category: CatalogCategory.WAX,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.FEMALE,
      groupKey: "body",
      titleRu: "Голени",
      subtitleRu: "25 мин",
      price: 1400,
      durationMin: 25,
    }),
    row({
      category: CatalogCategory.WAX,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.FEMALE,
      groupKey: "body",
      titleRu: "Бёдра",
      subtitleRu: "25 мин",
      price: 1600,
      durationMin: 25,
    }),
    row({
      category: CatalogCategory.WAX,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.FEMALE,
      groupKey: "body",
      titleRu: "Ноги полностью",
      subtitleRu: "45 мин",
      price: 2800,
      durationMin: 45,
    }),
    row({
      category: CatalogCategory.WAX,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.FEMALE,
      groupKey: "body",
      titleRu: "Живот (линия)",
      subtitleRu: "5 мин",
      price: 500,
      durationMin: 5,
    }),
    row({
      category: CatalogCategory.WAX,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.FEMALE,
      groupKey: "body",
      titleRu: "Живот полностью",
      subtitleRu: "20 мин",
      price: 1400,
      durationMin: 20,
    }),
    row({
      category: CatalogCategory.WAX,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.FEMALE,
      groupKey: "body",
      titleRu: "Спина полностью",
      subtitleRu: "35 мин",
      price: 2200,
      durationMin: 35,
    }),
    row({
      category: CatalogCategory.WAX,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.FEMALE,
      groupKey: "body",
      titleRu: "Ягодицы",
      subtitleRu: "20 мин",
      price: 1600,
      durationMin: 20,
    }),
    // WAX FEMALE intimate
    row({
      category: CatalogCategory.WAX,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.FEMALE,
      groupKey: "intimate",
      titleRu: "Бикини классическое",
      subtitleRu: "15 мин",
      price: 1200,
      durationMin: 15,
    }),
    row({
      category: CatalogCategory.WAX,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.FEMALE,
      groupKey: "intimate",
      titleRu: "Бикини глубокое",
      subtitleRu: "25 мин",
      price: 1800,
      durationMin: 25,
    }),
    row({
      category: CatalogCategory.WAX,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.FEMALE,
      groupKey: "intimate",
      titleRu: "Тотальное бикини",
      subtitleRu: "35 мин",
      price: 2400,
      durationMin: 35,
    }),
    // WAX MALE face
    row({
      category: CatalogCategory.WAX,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.MALE,
      groupKey: "face",
      titleRu: "Шея / контур бороды",
      subtitleRu: "15 мин",
      price: 1000,
      durationMin: 15,
    }),
    // WAX MALE body
    row({
      category: CatalogCategory.WAX,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.MALE,
      groupKey: "body",
      titleRu: "Подмышки",
      subtitleRu: "15 мин",
      price: 1000,
      durationMin: 15,
    }),
    row({
      category: CatalogCategory.WAX,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.MALE,
      groupKey: "body",
      titleRu: "Спина полностью",
      subtitleRu: "50 мин",
      price: 3500,
      durationMin: 50,
    }),
    row({
      category: CatalogCategory.WAX,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.MALE,
      groupKey: "body",
      titleRu: "Плечи",
      subtitleRu: "30 мин",
      price: 2000,
      durationMin: 30,
    }),
    row({
      category: CatalogCategory.WAX,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.MALE,
      groupKey: "body",
      titleRu: "Грудь",
      subtitleRu: "35 мин",
      price: 2200,
      durationMin: 35,
    }),
    row({
      category: CatalogCategory.WAX,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.MALE,
      groupKey: "body",
      titleRu: "Живот",
      subtitleRu: "25 мин",
      price: 1800,
      durationMin: 25,
    }),
    row({
      category: CatalogCategory.WAX,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.MALE,
      groupKey: "body",
      titleRu: "Ягодицы",
      subtitleRu: "30 мин",
      price: 2000,
      durationMin: 30,
    }),
    row({
      category: CatalogCategory.WAX,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.MALE,
      groupKey: "body",
      titleRu: "Голени",
      subtitleRu: "30 мин",
      price: 2000,
      durationMin: 30,
    }),
    row({
      category: CatalogCategory.WAX,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.MALE,
      groupKey: "body",
      titleRu: "Ноги полностью",
      subtitleRu: "60 мин",
      price: 3800,
      durationMin: 60,
    }),
    row({
      category: CatalogCategory.WAX,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.MALE,
      groupKey: "body",
      titleRu: "Руки полностью",
      subtitleRu: "35 мин",
      price: 2400,
      durationMin: 35,
    }),
    // WAX MALE intimate
    row({
      category: CatalogCategory.WAX,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.MALE,
      groupKey: "intimate",
      titleRu: "Интимная зона (мужская)",
      subtitleRu: "30 мин",
      price: 2000,
      durationMin: 30,
    }),
    // LASER FEMALE face
    row({
      category: CatalogCategory.LASER,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.FEMALE,
      groupKey: "face",
      titleRu: "Верхняя губа",
      subtitleRu: "5 мин",
      price: 800,
      durationMin: 5,
    }),
    row({
      category: CatalogCategory.LASER,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.FEMALE,
      groupKey: "face",
      titleRu: "Подбородок",
      subtitleRu: "5 мин",
      price: 900,
      durationMin: 5,
    }),
    row({
      category: CatalogCategory.LASER,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.FEMALE,
      groupKey: "face",
      titleRu: "Щёки и скулы",
      subtitleRu: "10 мин",
      price: 1400,
      durationMin: 10,
    }),
    row({
      category: CatalogCategory.LASER,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.FEMALE,
      groupKey: "face",
      titleRu: "Лицо полностью",
      subtitleRu: "20 мин",
      price: 2800,
      durationMin: 20,
    }),
    // LASER FEMALE body
    row({
      category: CatalogCategory.LASER,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.FEMALE,
      groupKey: "body",
      titleRu: "Подмышки",
      subtitleRu: "10 мин",
      price: 1500,
      durationMin: 10,
    }),
    row({
      category: CatalogCategory.LASER,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.FEMALE,
      groupKey: "body",
      titleRu: "Предплечья",
      subtitleRu: "15 мин",
      price: 2200,
      durationMin: 15,
    }),
    row({
      category: CatalogCategory.LASER,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.FEMALE,
      groupKey: "body",
      titleRu: "Руки полностью",
      subtitleRu: "20 мин",
      price: 3200,
      durationMin: 20,
    }),
    row({
      category: CatalogCategory.LASER,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.FEMALE,
      groupKey: "body",
      titleRu: "Голени",
      subtitleRu: "20 мин",
      price: 2800,
      durationMin: 20,
    }),
    row({
      category: CatalogCategory.LASER,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.FEMALE,
      groupKey: "body",
      titleRu: "Бёдра",
      subtitleRu: "25 мин",
      price: 3200,
      durationMin: 25,
    }),
    row({
      category: CatalogCategory.LASER,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.FEMALE,
      groupKey: "body",
      titleRu: "Ноги полностью",
      subtitleRu: "40 мин",
      price: 5500,
      durationMin: 40,
    }),
    row({
      category: CatalogCategory.LASER,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.FEMALE,
      groupKey: "body",
      titleRu: "Живот (линия)",
      subtitleRu: "10 мин",
      price: 1200,
      durationMin: 10,
    }),
    row({
      category: CatalogCategory.LASER,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.FEMALE,
      groupKey: "body",
      titleRu: "Живот полностью",
      subtitleRu: "20 мин",
      price: 2800,
      durationMin: 20,
    }),
    row({
      category: CatalogCategory.LASER,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.FEMALE,
      groupKey: "body",
      titleRu: "Спина полностью",
      subtitleRu: "30 мин",
      price: 4500,
      durationMin: 30,
    }),
    // LASER FEMALE intimate
    row({
      category: CatalogCategory.LASER,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.FEMALE,
      groupKey: "intimate",
      titleRu: "Бикини классическое",
      subtitleRu: "15 мин",
      price: 2000,
      durationMin: 15,
    }),
    row({
      category: CatalogCategory.LASER,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.FEMALE,
      groupKey: "intimate",
      titleRu: "Бикини глубокое",
      subtitleRu: "20 мин",
      price: 3200,
      durationMin: 20,
    }),
    row({
      category: CatalogCategory.LASER,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.FEMALE,
      groupKey: "intimate",
      titleRu: "Тотальное бикини",
      subtitleRu: "30 мин",
      price: 4500,
      durationMin: 30,
    }),
    // LASER MALE face
    row({
      category: CatalogCategory.LASER,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.MALE,
      groupKey: "face",
      titleRu: "Борода (контур / шея)",
      subtitleRu: "15 мин",
      price: 2000,
      durationMin: 15,
    }),
    // LASER MALE body
    row({
      category: CatalogCategory.LASER,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.MALE,
      groupKey: "body",
      titleRu: "Подмышки",
      subtitleRu: "10 мин",
      price: 1800,
      durationMin: 10,
    }),
    row({
      category: CatalogCategory.LASER,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.MALE,
      groupKey: "body",
      titleRu: "Спина полностью",
      subtitleRu: "45 мин",
      price: 6500,
      durationMin: 45,
    }),
    row({
      category: CatalogCategory.LASER,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.MALE,
      groupKey: "body",
      titleRu: "Плечи",
      subtitleRu: "25 мин",
      price: 3500,
      durationMin: 25,
    }),
    row({
      category: CatalogCategory.LASER,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.MALE,
      groupKey: "body",
      titleRu: "Грудь",
      subtitleRu: "30 мин",
      price: 4000,
      durationMin: 30,
    }),
    row({
      category: CatalogCategory.LASER,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.MALE,
      groupKey: "body",
      titleRu: "Живот",
      subtitleRu: "20 мин",
      price: 3200,
      durationMin: 20,
    }),
    row({
      category: CatalogCategory.LASER,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.MALE,
      groupKey: "body",
      titleRu: "Ягодицы",
      subtitleRu: "25 мин",
      price: 3500,
      durationMin: 25,
    }),
    row({
      category: CatalogCategory.LASER,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.MALE,
      groupKey: "body",
      titleRu: "Голени",
      subtitleRu: "25 мин",
      price: 3800,
      durationMin: 25,
    }),
    row({
      category: CatalogCategory.LASER,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.MALE,
      groupKey: "body",
      titleRu: "Ноги полностью",
      subtitleRu: "55 мин",
      price: 7500,
      durationMin: 55,
    }),
    row({
      category: CatalogCategory.LASER,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.MALE,
      groupKey: "body",
      titleRu: "Руки полностью",
      subtitleRu: "30 мин",
      price: 4500,
      durationMin: 30,
    }),
    // LASER MALE intimate
    row({
      category: CatalogCategory.LASER,
      type: CatalogItemType.ZONE,
      gender: CatalogGender.MALE,
      groupKey: "intimate",
      titleRu: "Интимная зона (мужская)",
      subtitleRu: "20 мин",
      price: 3500,
      durationMin: 20,
    }),
    // ELECTRO face zones (bookable, default 15 min session)
    row({
      category: CatalogCategory.ELECTRO,
      type: CatalogItemType.INFO,
      gender: CatalogGender.UNISEX,
      groupKey: "face",
      titleRu: "Верхняя губа",
      subtitleRu: null,
      price: 900,
      durationMin: 15,
    }),
    row({
      category: CatalogCategory.ELECTRO,
      type: CatalogItemType.INFO,
      gender: CatalogGender.UNISEX,
      groupKey: "face",
      titleRu: "Подбородок",
      subtitleRu: null,
      price: 900,
      durationMin: 15,
    }),
    row({
      category: CatalogCategory.ELECTRO,
      type: CatalogItemType.INFO,
      gender: CatalogGender.UNISEX,
      groupKey: "face",
      titleRu: "Щёки / скулы",
      subtitleRu: null,
      price: 900,
      durationMin: 15,
    }),
    row({
      category: CatalogCategory.ELECTRO,
      type: CatalogItemType.INFO,
      gender: CatalogGender.UNISEX,
      groupKey: "face",
      titleRu: "Брови",
      subtitleRu: null,
      price: 900,
      durationMin: 15,
    }),
    row({
      category: CatalogCategory.ELECTRO,
      type: CatalogItemType.INFO,
      gender: CatalogGender.UNISEX,
      groupKey: "face",
      titleRu: "Шея",
      subtitleRu: null,
      price: 900,
      durationMin: 15,
    }),
    // ELECTRO body zones (bookable, default 15 min session)
    row({
      category: CatalogCategory.ELECTRO,
      type: CatalogItemType.INFO,
      gender: CatalogGender.UNISEX,
      groupKey: "body",
      titleRu: "Ареолы",
      subtitleRu: null,
      price: 900,
      durationMin: 15,
    }),
    row({
      category: CatalogCategory.ELECTRO,
      type: CatalogItemType.INFO,
      gender: CatalogGender.UNISEX,
      groupKey: "body",
      titleRu: "Белая линия живота",
      subtitleRu: null,
      price: 900,
      durationMin: 15,
    }),
    row({
      category: CatalogCategory.ELECTRO,
      type: CatalogItemType.INFO,
      gender: CatalogGender.UNISEX,
      groupKey: "body",
      titleRu: "Пальцы рук / ног",
      subtitleRu: null,
      price: 900,
      durationMin: 15,
    }),
    row({
      category: CatalogCategory.ELECTRO,
      type: CatalogItemType.INFO,
      gender: CatalogGender.UNISEX,
      groupKey: "body",
      titleRu: "Единичные волосы",
      subtitleRu: null,
      price: 900,
      durationMin: 15,
    }),
    // ELECTRO INFO other
    row({
      category: CatalogCategory.ELECTRO,
      type: CatalogItemType.INFO,
      gender: CatalogGender.UNISEX,
      groupKey: "info",
      titleRu: "Финальная доработка после лазера",
      subtitleRu: null,
      price: null,
      durationMin: null,
    }),
    // ELECTRO TIME offers
    row({
      category: CatalogCategory.ELECTRO,
      type: CatalogItemType.OFFER,
      gender: CatalogGender.UNISEX,
      groupKey: "time",
      titleRu: "15 минут",
      subtitleRu: null,
      price: 900,
      durationMin: 15,
    }),
    row({
      category: CatalogCategory.ELECTRO,
      type: CatalogItemType.OFFER,
      gender: CatalogGender.UNISEX,
      groupKey: "time",
      titleRu: "30 минут",
      subtitleRu: null,
      price: 1700,
      durationMin: 30,
    }),
    row({
      category: CatalogCategory.ELECTRO,
      type: CatalogItemType.OFFER,
      gender: CatalogGender.UNISEX,
      groupKey: "time",
      titleRu: "45 минут",
      subtitleRu: null,
      price: 2400,
      durationMin: 45,
    }),
    row({
      category: CatalogCategory.ELECTRO,
      type: CatalogItemType.OFFER,
      gender: CatalogGender.UNISEX,
      groupKey: "time",
      titleRu: "60 минут",
      subtitleRu: null,
      price: 3000,
      durationMin: 60,
    }),
    row({
      category: CatalogCategory.ELECTRO,
      type: CatalogItemType.OFFER,
      gender: CatalogGender.UNISEX,
      groupKey: "time",
      titleRu: "90 минут",
      subtitleRu: null,
      price: 4200,
      durationMin: 90,
    }),
    row({
      category: CatalogCategory.ELECTRO,
      type: CatalogItemType.OFFER,
      gender: CatalogGender.UNISEX,
      groupKey: "time",
      titleRu: "120 минут",
      subtitleRu: null,
      price: 5200,
      durationMin: 120,
    }),
    // MASSAGE
    row({
      category: CatalogCategory.MASSAGE,
      type: CatalogItemType.OFFER,
      gender: CatalogGender.UNISEX,
      groupKey: "massage",
      titleRu: "Классический массаж",
      subtitleRu: "60 мин",
      price: 2000,
      durationMin: 60,
    }),
    row({
      category: CatalogCategory.MASSAGE,
      type: CatalogItemType.OFFER,
      gender: CatalogGender.UNISEX,
      groupKey: "massage",
      titleRu: "Расслабляющий массаж",
      subtitleRu: "60 мин",
      price: 2000,
      durationMin: 60,
    }),
    row({
      category: CatalogCategory.MASSAGE,
      type: CatalogItemType.OFFER,
      gender: CatalogGender.UNISEX,
      groupKey: "massage",
      titleRu: "Спортивный массаж",
      subtitleRu: "60 мин",
      price: 2200,
      durationMin: 60,
    }),
    row({
      category: CatalogCategory.MASSAGE,
      type: CatalogItemType.OFFER,
      gender: CatalogGender.UNISEX,
      groupKey: "massage",
      titleRu: "Лимфодренажный массаж",
      subtitleRu: "60 мин",
      price: 2200,
      durationMin: 60,
    }),
  ]

  await prisma.catalogItem.createMany({ data: items })
}
